"""Generate typed `.pyi` stubs for every hook in a project's skins.

Drop the output at ``.elysium/stubs/<skin_id>.pyi`` and add that path
to your project's ``MYPY_PATH`` (or PyCharm picks it up automatically
via its ``Mark Directory As → Sources Root``). Then::

    win["play.click"].fire()   # autocomplete + type-checked

works because the generated stub declares ``play.click`` as an
``EventHook``, ``track.title.text`` as a ``TextHook``, etc.
"""
from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


_HOOK_TYPES = {
    "event": "EventHook",
    "text":  "TextHook",
    "image": "ImageHook",
    "value": "ValueHook",
    "state": "StateHook",
    "slot":  "SlotHook",
    "style": "StyleHook",
}


@dataclass
class _Hook:
    name: str
    kind: str
    states: list[str]
    range:  tuple[float, float] | None


def _walk(node: dict) -> Iterable[_Hook]:
    for h in node.get("hooks", []) or []:
        rng = h.get("range")
        yield _Hook(
            name=h.get("name", ""),
            kind=h.get("type", "event"),
            states=list(h.get("states", []) or []),
            range=(tuple(rng) if rng else None),  # type: ignore[arg-type]
        )
    for c in node.get("children", []) or []:
        yield from _walk(c)


def generate_for_skin(skin_dir: str | Path,
                       output_dir: str | Path = ".elysium/stubs") -> Path:
    skin = Path(skin_dir).resolve()
    doc_path = skin / "document.json"
    if not doc_path.is_file():
        raise FileNotFoundError(doc_path)
    doc = json.loads(doc_path.read_text())
    out = Path(output_dir).resolve()
    out.mkdir(parents=True, exist_ok=True)

    manifest = json.loads((skin / "manifest.json").read_text())
    skin_id = manifest.get("id", skin.stem).replace(".", "_")
    target  = out / f"{skin_id}.pyi"

    hooks = list(_walk(doc.get("root", {})))
    lines = [
        '"""Generated by `elysium.stubgen`. Do not edit by hand."""',
        "from typing import Literal, overload",
        "from elysium import Window",
        "",
        "EventHook = TextHook = ImageHook = ValueHook = SlotHook = StyleHook = object",
        "",
        "class StateHook:",
        "    def __init__(self, *states: str) -> None: ...",
        "    def set(self, s: str, /) -> None: ...",
        "",
        f"# {len(hooks)} hooks declared in {skin.name}",
        "",
        "class _Hooks:",
    ]
    for h in hooks:
        if not h.name: continue
        if h.kind == "state":
            states = ", ".join(f"'{s}'" for s in h.states)
            ann = f"StateHook  # states: [{states}]"
        elif h.kind == "value":
            lo, hi = h.range or (0.0, 1.0)
            ann = f"ValueHook  # range: [{lo}, {hi}]"
        else:
            ann = _HOOK_TYPES.get(h.kind, "object")
        lines.append(f"    {h.name.replace('.', '_')}: {ann}")
    lines.extend([
        "",
        "class TypedWindow(Window):",
        "    @overload",
    ])
    for h in hooks:
        if not h.name: continue
        lit = f"Literal[{h.name!r}]"
        ret = _HOOK_TYPES.get(h.kind, "object")
        lines.append(f"    def __getitem__(self, key: {lit}) -> {ret}: ...")
        lines.append("    @overload")
    lines.append("    def __getitem__(self, key: str) -> object: ...")

    target.write_text("\n".join(lines) + "\n")
    return target


def generate_for_workspace(root: str | Path = ".",
                            output_dir: str | Path = ".elysium/stubs"
                            ) -> list[Path]:
    """Recursively find every `.esk/` in `root` and emit a stub for each."""
    out: list[Path] = []
    for esk in Path(root).rglob("*.esk"):
        if esk.is_dir() and (esk / "document.json").is_file():
            out.append(generate_for_skin(esk, output_dir))
    return out


__all__ = ["generate_for_skin", "generate_for_workspace"]
