//! Per-session token authentication. Token is generated by the app on
//! startup, stored in `~/.elysium/sessions/<pid>.token`, and required in
//! every `Hello` from the Designer / IDE plugin.

use std::path::PathBuf;

pub fn session_dir() -> PathBuf {
    let home = std::env::var("HOME")
        .or_else(|_| std::env::var("USERPROFILE"))
        .unwrap_or_else(|_| ".".into());
    PathBuf::from(home).join(".elysium").join("sessions")
}
